version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8001:8001"
    volumes:
      - .:/code
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    command: daphne -b 0.0.0.0 -p 8000 config.asgi:application
    env_file:
      - .env
  redis:
    restart: always
    image: 'redis:latest'
    ports:
      - '6379:6379'
    hostname: redis
